### ISSUE TITLE
Fails on create

### ISSUE THREAD

**Issue by leoncvlt** [scottmcpherson/meteor-io#1]
Can't seem to be able to create a new project, here's the output:

```
C:\Users\leonardoc
λ io create io-test
fs.js:856
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\leonardoc\AppData\Roaming\npm\node_modules\meteor-io\bin\lib\generators'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at requireDir (C:\Users\leonardoc\AppData\Roaming\npm\node_modules\meteor-io\node_modules\require-dir\index.js:25:20)
    at Command.loadUserGenerators (C:\Users\leonardoc\AppData\Roaming\npm\node_modules\meteor-io\lib\command.js:69:29)
    at Command.run (C:\Users\leonardoc\AppData\Roaming\npm\node_modules\meteor-io\lib\command.js:34:10)
    at Object.<anonymous> (C:\Users\leonardoc\AppData\Roaming\npm\node_modules\meteor-io\bin\io:7:13)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

Using nodejs 5.0.0 on win7 x64

**Comment by scottmcpherson** [comment]
Thanks @leoncvlt. Unfortunately I don't have a windows machine but if anybody else is able to figure this out, go for it!
