### ISSUE TITLE
Create project fail.

### ISSUE THREAD

**Issue by cihanzengin** [scottmcpherson/meteor-io#13]
i follow your tutorial here but i'm getting error everytime..

npm install -g meteor-io
**ok passed.**

io
*_ok passed
*_
After you specify a directory, io will create a director that looks similar to this:
yes, io created for me some directory. 

io create project-name
*_and ....
*_

```
mac$ io create project-name
fs.js:856
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/meteor-io/lib/Desktop/meteormain/io/generators'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at requireDir (/usr/local/lib/node_modules/meteor-io/node_modules/require-dir/index.js:25:20)
    at Command.loadUserGenerators (/usr/local/lib/node_modules/meteor-io/lib/command.js:83:29)
    at Command.run (/usr/local/lib/node_modules/meteor-io/lib/command.js:35:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-io/bin/io:7:13)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)


```

**Comment by scottmcpherson** [comment]
Sorry I'm responding @cihanzengin. I'm getting ready to push a change that will hopefully fix this.

**Comment by elidiazgt** [comment]
Im getting this at create a new project

![screenshot 2016-11-28 16 38 42](https://cloud.githubusercontent.com/assets/11800064/20689058/2c0e89a6-b589-11e6-9eb8-416a6ed2f7b7.png)

**Comment by gauravkeerthi** [comment]
+1 for the same problem as @elidiazgt
