### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by rfox90** [scottmcpherson/meteor-io#2]
Running on windows:

```
D:\Documents\GitHub>npm install -g meteor-io
D:\AppData\Roaming\npm\io -> D:\AppData\Roaming\npm\node_modules\meteor-io\bin\i
o
meteor-io@0.5.4 D:\AppData\Roaming\npm\node_modules\meteor-io
├── single-line-log@1.0.0
├── dotenv@1.2.0
├── underscore@1.8.3
├── minimist@1.1.2
├── require-dir@0.3.0
├── readline-sync@1.2.20
├── cli-table@0.3.1 (colors@1.0.3)
├── fs-extra@0.22.1 (jsonfile@2.2.3, graceful-fs@4.1.2, rimraf@2.4.3)
├── handlebars@3.0.3 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)
├── lodash@3.10.1
└── cli-color@1.0.0 (ansi-regex@1.1.1, d@0.1.1, timers-ext@0.1.0, es6-iterator@0
.1.3, memoizee@0.3.9, es5-ext@0.10.8)

D:\Documents\GitHub>io
Error: unrecognized flag --harmony-rest-parameters
Try --help for options

D:\AppData\Roaming\npm\node_modules\meteor-io\lib\command.js:9
class Command extends Utils {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\AppData\Roaming\npm\node_modules\meteor-io\lib\io.
js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Let me know if you need any diagnostic steps.

**Comment by scottmcpherson** [comment]
Hey @rfox90, what version of node are you running?

**Comment by rfox90** [comment]
An Ancient version. I'm so sorry :) Works on latest.

**Comment by scottmcpherson** [comment]
Nice! Glad it's working :)
