### ISSUE TITLE
Issue during Create for the latest version in mac

### ISSUE THREAD

**Issue by adiAtMiddleware** [scottmcpherson/meteor-io#3]
io create test
Error: unrecognized flag --harmony-rest-parameters
Try --help for options

/usr/local/lib/node_modules/meteor-io/lib/command.js:9
class Command extends Utils {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-io/lib/io.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by scottmcpherson** [comment]
Hey @adiAtMiddleware, what version of node are you running?

**Comment by adiAtMiddleware** [comment]
Here is the version:v0.10.26

**Comment by adiAtMiddleware** [comment]
upgraded to v4.2.1, and it is working fine
