### ISSUE TITLE
Error (node: bad option: --harmony-rest-parameters)

### ISSUE THREAD

**Issue by M165437** [scottmcpherson/meteor-io#5]
After installing meteor-io with

```
$ npm install -g meteor-io
```

I get an error on whatever io command I try

```
$ io --help
node: bad option: --harmony-rest-parameters
```

Any idea? Thanks!

**Comment by scottmcpherson** [comment]
Hey @M165437, what version of node are you running?

**Comment by M165437** [comment]
Good point. I was running v0.12.2. Did the upgrade and it works. Thank you!

**Comment by scottmcpherson** [comment]
Glad that did the trick @M165437.

Quite a few people are running into this same problem, so I'm going to leave this open for reference for now.

**Comment by samnarain** [comment]
@scottmcpherson its definitely the node version. Awesome work!

**Comment by jazzmac** [comment]
Won't work with node 6.1.0.

**Comment by scottmcpherson** [comment]
@jazzmac Can you try uninstalling io, and then installing the latest directly from GitHub instead of NPM and letting me know if everything is working on your end so I can update NPM?

The command to install from GitHub:
`git clone https://github.com/scottmcpherson/meteor-io.git` 

And then cd into that directory and run:
`npm link`

**Comment by jazzmac** [comment]
I got this error:

io  
fs.js:945
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/seixas/io/meteor-io/bin/lib/generators'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at requireDir (/Users/seixas/bin/io/meteor-io/node_modules/require-dir/index.js:25:20)
    at Command.loadUserGenerators (/Users/seixas/bin/io/meteor-io/lib/command.js:78:31)
    at Command.run (/Users/seixas/bin/io/meteor-io/lib/command.js:31:10)
    at Object.<anonymous> (/Users/seixas/bin/io/meteor-io/bin/io:7:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
